finchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from. import views

urlpatterns = [
    path('', views.home),
    path('about/', views.about, name = 'about'),
    path('finches/', views.finches_index, name= 'index'),
    path('finches/<int:finch_id>/',views.finch_detail, name = 'detail'),
    path('finches/create/', views.FinchCreate.as_view(), name = 'finches_create'),
    path('finches/<int:pk>/update/',views.FinchUpdate.as_view(), name='finches_update'),
    path('finches/<int:pk>/delete/',views.FinchDelete.as_view(), name='finches_delete'),
    path('finches/<int:finch_id>/add_feeding/',views.add_feeding,name='add_feeding'),

    path('cages/', views.CageList.as_view(), name='cages_index'),
    path('cages/<int:pk>/', views.CageDetail.as_view(), name='cages_detail'),
    path('cages/create/', views.CageCreate.as_view(), name='cages_create'),
    path('cages/<int:pk>/update/', views.CageUpdate.as_view(), name='cages_update'),
    path('cages/<int:pk>/delete/', views.CageDelete.as_view(), name='cages_delete'),
    path('finches/<int:finch_id>/assoc_cage/<int:cage_id>/', views.assoc_cage, name='assoc_cage'),
    path('finches/<int:finch_id>/unassoc_cage/<int:cage_id>/', views.unassoc_cage, name='unassoc_cage'),

]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date

MEALS = (
    ('B', 'Breakfast'),
    ('L','Lunch'),
    ('D','Dinner'),
)



# Create your models here.

class Cage(models.Model):
    name = models.CharField(max_length=12, default='')
    material = models.CharField(max_length=30)
    color = models.CharField(max_length=40)
    size = models.IntegerField()

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('cages_detail', kwargs={'pk': self.id})
    


class Finch(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    count = models.IntegerField()
    cages = models.ManyToManyField(Cage)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'finch_id': self.id})

class Feeding(models.Model):
    date = models.DateField('Feeding Date')
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
    )

    # create a finch_id FK

    finch = models.ForeignKey(
        Finch,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
  class Meta:
    model = Feeding
    fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Finch, Cage
from .forms import FeedingForm



# Create your views here.

def home(request):
    return render(request,'home.html')

def about(request):
    return render(request,'about.html')

def finches_index(request):
    finches = Finch.objects.all()
    return render(request,'finches/index.html',{
        'finches': finches
    })
    
def finch_detail(request, finch_id):
    finch = Finch.objects.get(id=finch_id)

    id_list = finch.cages.all().values_list('id')
    cages_that_dont_have = Cage.objects.exclude(id__in=id_list)

    feeding_form = FeedingForm()
    return render(request,'finches/detail.html', {
        'finch': finch, 'feeding_form': feeding_form,
        'cages': cages_that_dont_have
    })

def assoc_cage(request, finch_id, cage_id):
    Finch.objects.get(id=finch_id).cages.add(cage_id)
    return redirect('detail', finch_id=finch_id)

def unassoc_cage(request, finch_id, cage_id):
    Finch.objects.get(id=finch_id).cages.remove(cage_id)
    return redirect('detail', finch_id=finch_id)

class FinchCreate(CreateView):
    model = Finch
    fields = '__all__'

class FinchUpdate(UpdateView):
    model = Finch
    fields = ('count','name')

class FinchDelete(DeleteView):
    model = Finch
    success_url = '/finches/'

def add_feeding(request,finch_id):
    form = FeedingForm(request.POST)
    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.finch_id = finch_id
        new_feeding.save()
    return redirect('detail', finch_id=finch_id)

class CageList(ListView):
  model = Cage

class CageDetail(DetailView):
    model = Cage
    

class CageCreate(CreateView):
  model = Cage
  fields = '__all__'

class CageUpdate(UpdateView):
  model = Cage
  fields = ['name', 'color','material', 'size']

class CageDelete(DeleteView):
  model = Cage
  success_url = '/cages'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
<h1>About the Finch Collector</h1>
<hr>
<p>Hire the Finch Collector!</p>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Finch Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper blue">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp; Finch Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'cages_create' %}">Add a Cage</a></li>
          <li><a href="{% url 'cages_index' %}">View All Cages</a></li>
          <li><a href="{% url 'finches_create' %}">Add a Finch </a></li>
          <li><a href="{% url 'index' %}">View All Finches</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer blue">
    <div class="right">All Rights Reserved, &copy; 2024 Finch Collector &nbsp;</div>
  </footer>
</body>

</html>

main_app/templates/finches/detail.html
{% extends 'base.html' %}
{% block content %}
<h1>Finch Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ finch.name }}</span>
        <p>Breed: {{ finch.breed }}</p>
        <p>Count: {{ finch.count }}</p>
        <p>Description: {{ finch.description }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'finches_update' finch.id %}">Edit</a>
        <a href="{% url 'finches_delete' finch.id %}">Delete</a>
      </div>
    </div>
  </div>

  <div class="col s6">
    <form action="{% url 'add_feeding' finch.id %}" method="POST">
      {% csrf_token %}
      <!-- Render the inputs -->
      {{ feeding_form.as_p }}
      <input type="submit" class="btn" value="Add Feeding">
    </form>
    <br>
    {% if finch.fed_for_today %}
    <div class="card-panel teal-text center-align">{{finch.name}} has been fed all meals for today</div>
    {% else %}
    <div class="card-panel red-text center-align">{{finch.name}} might be hungry</div>
    {% endif %}
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Meal</th>
        </tr>
      </thead>
      <tbody>
        {% for feeding in finch.feeding_set.all %}
        <tr>
          <td>{{feeding.date}}</td>
          <td>{{feeding.get_meal_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<!-- Add a Cage -->

<div class="row">
  <div class="col s6">
    <h3>{{ finch.name }}'s Cage</h3>
    {% if finch.cages.count %}
    {% for cage in finch.cages.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          A <span class="{{ cage.color.lower }}-text">{{ cage.color }}</span> {{ cage.material }} {{ cage.size }}
        </span>
      </div>

      <div class="action">

        <form action="{% url 'unassoc_cage' finch.id cage.id %}" method="POST">
          {% csrf_token %}
          <input type="submit" value="Remove" class="btn red">
        </form>

      </div>


    </div>
    {% endfor %}
    {% else %}

    <h5>{{finch.name}} has no Cage yet :</h5>

    {% endif %}
  </div>

  <div class="col s6">
    <h3>Available Cages</h3>
    {% for cage in cages %}
    <div class="card">
      <div class="card-content">

        <span class="card-title">
          A <span class="{{ cage.color.lower }}-text">{{ cage.color }}</span> {{ cage.size }}
        </span>
      </div>
      <div class="action">
        <form action="{% url 'assoc_cage' finch.id cage.id %}" method="POST">
          {% csrf_token %}
          <input type="submit" value="Add" class="btn green">
        </form>
      </div>

    </div>
    {% endfor %}
  </div>

</div>

<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const selectEl = document.getElementById('id_meal');
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/finches/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Finch List</h1>

{% for finch in finches %}
<a href="/finches/{{ finch.id}}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ finch.name }}</span>
            <p>Breed: {{ finch.breed }}</p>
            <p>Description: {{ finch.description }}</p>
            {% if finch.count > 10 %}

            <p>count: {{finch.count}}</p>

            {% else %}
            <p>conservation status:endangered </p>

            {% endif %}

        </div>
    </div>
</a>

{% endfor %}



{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <h1>Finch Collector</h1>
{% endblock %}

main_app/templates/main_app/cage_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Cage</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'cages_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/cage_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Cage Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ cage.name }}</span>
        <p>Material: {{ cage.material }}</p>
        <p>Color: {{ cage.color }}</p>
        <p>Size: {{ cage.size }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'cages_update' cage.id %}">Edit</a>
        <a href="{% url 'cages_delete' cage.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/cage_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Cage</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/cage_list.html
{% extends 'base.html' %}
{% block content %}

<h1> Cage List</h1>

{% for cage in cage_list %}
  <a href="{% url 'cages_detail' cage.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ cage.name }}</span>
            <p>Color: {{ cage.color }}</p>
            <p>Size: {{ cage.size }}</p>
            <p>Material: {{ cage.material }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/finch_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Are you sure you want to delete {{object.name}}? </h1>
<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, I want to Delete {{object.name}}" class="btn red">
    <a class="btn green" href="{% url 'detail' object.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/finch_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Update {{object.name}}'s Details </h1>

{% else %}
<h1>Create Finch</h1>
{% endif %}

<form action="" method="POST">

    {% csrf_token %}
     
    <table>
        {{form.as_table}}
    </table>

    <input type="submit" value="Submit" class="btn blue">

</form>

{% endblock %}